# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cameramen',
            fields=[
                ('cameraman_id', models.AutoField(primary_key=True, serialize=False)),
                ('cameraman_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film_writers',
            fields=[
                ('film_writer_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_writer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filmmakers',
            fields=[
                ('filmmaker_id', models.AutoField(primary_key=True, serialize=False)),
                ('filmmaker_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('box_office_results', models.IntegerField()),
                ('cameraman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Cameramen')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Countries')),
                ('film_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Film_writers')),
                ('filmmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Filmmakers')),
                ('in_the_lead_role', models.ManyToManyField(to='db_app.Actors')),
            ],
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Producers'),
        ),
    ]
